DROP TABLE IF EXISTS Nutrition CASCADE;
DROP TABLE IF EXISTS Lactation CASCADE;
DROP TABLE IF EXISTS Feeding_plan CASCADE;
DROP TABLE IF EXISTS Diet CASCADE;
DROP TABLE IF EXISTS Cow CASCADE;
DROP TABLE IF EXISTS Feeds CASCADE;
DROP TABLE IF EXISTS Livestock_specialist CASCADE;

DROP TABLE IF EXISTS Breed CASCADE;
DROP TABLE IF EXISTS Day_Times CASCADE;
DROP TABLE IF EXISTS Season CASCADE;
DROP TABLE IF EXISTS Lactation_Phase CASCADE;
DROP TABLE IF EXISTS Feed_Type CASCADE;
DROP TABLE IF EXISTS Cow_Lactation_Diet_Count CASCADE;